export const isRequesting = state => state.getIn(['meta', 'requesting'])
export const getErrorMessage = state => state.getIn(['meta', 'errorMessage'])
export const getRecordCount = state => state.get('byId').count()
export const getRecord = (state, id) => state.getIn(['byId', id])
export const getRecords = state => state.get('byId').toList()
